NHSDP_Request_handling/NHSDP_Request_handling.WEB/Controllers/CourseController.cs
using AutoMapper;

using NHSDP_Request_handling.Core.Model;
using NHSDP_Request_handling.Logic.Interface;
using NHSDP_Request_handling.WEB.ViewModel;


namespace NHSDP_Request_handling.WEB.Controllers
{
    public class CourseController : CRUDControllerBase<Course, CourseVM>
    {
        public CourseController(IMapper mapper, ICRUDServiceBase<Course> courseService)
        {
            this.mapper = mapper;
            this.entityService = courseService;
        }
    }
}

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Controllers/InternshipController.cs
using AutoMapper;

using NHSDP_Request_handling.Core.Model;
using NHSDP_Request_handling.Logic.Interface;
using NHSDP_Request_handling.WEB.ViewModel;


namespace NHSDP_Request_handling.WEB.Controllers
{
    public class InternshipController : CRUDControllerBase<Internship, InternshipVM>
    {
        public InternshipController(IMapper mapper, ICRUDServiceBase<Internship> internshipService)
        {
            this.mapper = mapper;
            this.entityService = internshipService;
        }
    }
}

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Controllers/OfficeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NHSDP_Request_handling.Core.Model;
using NHSDP_Request_handling.Logic.Interface;
using NHSDP_Request_handling.WEB.ViewModel;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace NHSDP_Request_handling.WEB.Controllers
{
    public class OfficeController : CRUDControllerBase<Office, OfficeVM>
    {
        public OfficeController(IMapper mapper, ICRUDServiceBase<Office> officeController)
        {
            this.mapper = mapper;
            this.entityService = officeController;
        }
    }
}

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Controllers/ProgramController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using NHSDP_Request_handling.Core.Model;
using NHSDP_Request_handling.Logic.Interface;
using NHSDP_Request_handling.WEB.ViewModel;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace NHSDP_Request_handling.WEB.Controllers
{
    public class ProgramController : CRUDControllerBase<Core.Model.Program, ProgramVM>
    {
        private ICRUDServiceBase<Course> officeService;
        private ICRUDServiceBase<Internship> internshipService;

        public ProgramController(IMapper mapper, ICRUDServiceBase<Core.Model.Program> programService, 
            ICRUDServiceBase<Course> officeService, ICRUDServiceBase<Internship> internshipService)
        {
            this.mapper = mapper;
            this.entityService = programService;
            this.officeService = officeService;
            this.internshipService = internshipService;
        }

        public override async Task<IActionResult> CreateView()
        {
            IEnumerable<Course> offices = await officeService.GetAllAsync();
            ViewData["Courses"] = mapper.Map<IEnumerable<CourseVM>>(offices).Select(o =>
                                    new SelectListItem()
                                    {
                                        Text = o.Technology + ", " + o.HoursCount + " hours",
                                        Value = o.Id.ToString()
                                    }).ToList();

            IEnumerable<Internship> internships = await internshipService.GetAllAsync();
            ViewData["Internships"] = mapper.Map<IEnumerable<InternshipVM>>(internships).Select(i =>
                                        new SelectListItem()
                                        {
                                            Text = i.StartAt.Date.ToShortDateString() + "-" + i.EndAt.Date.ToShortDateString() 
                                                + ", " + i.EnrollmentState,
                                            Value = i.Id.ToString(),
                                        }).ToList();

            return await base.CreateView();
        }
    }
}

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Controllers/StudyingPlaceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using NHSDP_Request_handling.Core.Model;
using NHSDP_Request_handling.Logic.Interface;
using NHSDP_Request_handling.WEB.ViewModel;

using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace NHSDP_Request_handling.WEB.Controllers
{
    public class StudyingPlaceController : CRUDControllerBase<StudyingPlace, StudyingPlaceVM>
    {
        private ICRUDServiceBase<Office> officeService;
        private ICRUDServiceBase<Internship> internshipService;

        public StudyingPlaceController(IMapper mapper, ICRUDServiceBase<StudyingPlace> courseService, 
            ICRUDServiceBase<Office> officeService, ICRUDServiceBase<Internship> internshipService)
        {
            this.mapper = mapper;
            this.entityService = courseService;
            this.officeService = officeService;
            this.internshipService = internshipService;
        }

        public override async Task<IActionResult> CreateView()
        {
            IEnumerable<Office> offices = await officeService.GetAllAsync();
            ViewData["Offices"] = mapper.Map<IEnumerable<OfficeVM>>(offices).Select(o =>
                                    new SelectListItem()
                                    {
                                        Text = o.Adress,
                                        Value = o.Id.ToString()
                                    }).ToList();

            IEnumerable<Internship> internships = await internshipService.GetAllAsync();
            ViewData["Internships"] = mapper.Map<IEnumerable<InternshipVM>>(internships).Select(i =>
                                        new SelectListItem()
                                        {
                                            Text = i.StartAt.Date.ToShortDateString() + "-" + i.EndAt.Date.ToShortDateString() 
                                                + ", " + i.EnrollmentState,
                                            Value = i.Id.ToString(),
                                        }).ToList();

            return await base.CreateView();
        }

        public override async Task<IActionResult> Create(StudyingPlaceVM sp)
        {
            TempData["Message"] = await entityService.CreateAsync(mapper.Map<StudyingPlace>(sp));

            if (TempData["Message"] == null)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("CreateView");
        }
    }
}

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Course/CreateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.CourseVM

@{
    ViewData["Title"] = "Create course";
}

<h4>Create a new course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Technology" class="control-label"></label>
                <input asp-for="Technology" class="form-control" required/>
            </div>
            <div class="form-group">
                <label asp-for="HoursCount" class="control-label">Hours count</label>
                <input asp-for="HoursCount" class="form-control" type="number" min="2" required/>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Course/Index.cshtml
@using NHSDP_Request_handling.WEB.ViewModel;
@model IEnumerable<CourseVM>
@{
    ViewData["Title"] = "Courses";
}

<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Technology</th>
            <th>Hours count</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (CourseVM course in Model)
        {
            <tr>
                <td>@course.Id.ToString().Substring(0, 10) ...</td>
                <td>@course.Technology</td>
                <td>@course.HoursCount</td>
                <td><input type="button" value="Delete" onclick="@("window.location.href='" + @Url.Action("Delete", "Course") + "?id=" + course.Id + "'");" class="btn btn-primary" /></td>
                <td><input type="button" value="Edit" onclick="@("window.location.href='" + @Url.Action("UpdateView", "Course", course) + "'");" class="btn btn-primary" /></td>
            </tr>
        }
    </table>
</div>

<input type="button" value="Add course" onclick="@("window.location.href='" + @Url.Action("CreateView", "Course") + "'");" class="btn btn-primary" />

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Course/UpdateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.CourseVM

@{
    ViewData["Title"] = "Edit course";
}

<h4>Update course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div class="form-group">
                <input hidden asp-for="Id" value="@Model.Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Technology" class="control-label"></label>
                <input asp-for="Technology" value="@Model.Technology" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="HoursCount" class="control-label">Hours count</label>
                <input asp-for="HoursCount" value="@Model.HoursCount" class="form-control" type="number" min="2" required />
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Internship/Create.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.InternshipVM

@{
    ViewData["Title"] = "Add office";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h4>Create new internship</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="StartAt" class="control-label"></label>
                <input asp-for="StartAt" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EndAt" class="control-label"></label>
                <input asp-for="EndAt" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="MaxStudentsCount" class="control-label"></label>
                <input asp-for="MaxStudentsCount" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Internship/CreateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.InternshipVM

@{
    ViewData["Title"] = "Create internship";
}

<h4>Create new internship</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="StartAt" class="control-label">Start at</label>
                <input asp-for="StartAt" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="EndAt" class="control-label">End at</label>
                <input asp-for="EndAt" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="MaxStudentsCount" class="control-label">Maximum students count</label>
                <input asp-for="MaxStudentsCount" class="form-control" min="1" required />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Internship/Index.cshtml
@using NHSDP_Request_handling.WEB.ViewModel;
@model IEnumerable<InternshipVM>
@{
    ViewData["Title"] = "Internships";
}

<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Starting date</th>
            <th>End date</th>
            <th>Students count</th>
            <th>Maximum students count</th>
            <th>Enrollment state</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (InternshipVM internship in Model)
        {
            <tr>
                <td>@internship.Id.ToString().Substring(0, 10) ...</td>
                <td>@internship.StartAt.ToShortDateString()</td>
                <td>@internship.EndAt.ToShortDateString()</td>
                <td>@internship.StudentsCount</td>
                <td>@internship.MaxStudentsCount</td>
                <td>@internship.EnrollmentState</td>
                <td><input type="button" value="Delete" onclick="@("window.location.href='" + @Url.Action("Delete", "Internship") + "?id=" + internship.Id + "'");" class="btn btn-primary" /></td>
                <td><input type="button" value="Edit" onclick="@("window.location.href='" + @Url.Action("UpdateView", "Internship", internship) + "'");" class="btn btn-primary" /></td>
            </tr>
        }
    </table>
</div>

<input type="button" value="Create internship" onclick="@("window.location.href='" + @Url.Action("CreateView", "Internship") + "'");" class="btn btn-primary" />
<input type="button" value="View studying places" onclick="@("window.location.href='" + @Url.Action("Index", "StudyingPlace") + "'");" class="btn btn-primary" />
<input type="button" value="View programs" onclick="@("window.location.href='" + @Url.Action("Index", "Program") + "'");" class="btn btn-primary" />

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Internship/UpdateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.InternshipVM

@{
    ViewData["Title"] = "Edit internship";
}

<h4>Update office</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div class="form-group">
                <input hidden asp-for="Id" value="@Model.Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="StartAt" class="control-label">Start date</label>
                <input asp-for="StartAt" value="@Model.StartAt.Date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EndAt" class="control-label">End date</label>
                <input asp-for="EndAt" value="@Model.EndAt.Date" asp-format="{0:yyyy-MM-dd}" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="EnrollmentState" class="control-label">Enrollment state</label>
                <select asp-for="EnrollmentState" asp-items="ViewBag.EnrollmentStates" class="form-control" required>
                    <option value="InProgress">In progress</option>
                    <option value="Paused">Paused</option>
                    <option value="Stopped">Stopped</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="MaxStudentsCount" class="control-label">Maximum students count</label>
                <input asp-for="MaxStudentsCount" value="@Model.MaxStudentsCount" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="StudentsCount" class="control-label">Current students count</label>
                <input asp-for="StudentsCount" value="@Model.StudentsCount" class="form-control" required />
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Office/Create.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.OfficeVM

@{
    ViewData["Title"] = "Add office";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<h4>Add a new office</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="CabinetsCount" class="control-label"></label>
                <input asp-for="CabinetsCount" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Office/CreateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.OfficeVM

@{
    ViewData["Title"] = "Add office";
}

<h4>Add a new office</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="CabinetsCount" class="control-label">Cabinets count</label>
                <input asp-for="CabinetsCount" class="form-control" type="number" min="1" required />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Office/Index.cshtml
@using NHSDP_Request_handling.WEB.ViewModel;
@model IEnumerable<OfficeVM>
@{
    ViewData["Title"] = "Offices";
}

<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Adress</th>
            <th>Cabinets count</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (OfficeVM office in Model)
        {
            <tr>
                <td>@office.Id.ToString().Substring(0, 10) ...</td>
                <td>@office.Adress</td>
                <td>@office.CabinetsCount</td>
                <td><input type="button" value="Delete" onclick="@("window.location.href='" + @Url.Action("Delete", "Office") + "?id=" + office.Id + "'");" class="btn btn-primary" /></td>
                <td><input type="button" value="Edit" onclick="@("window.location.href='" + @Url.Action("UpdateView", "Office", office) + "'");" class="btn btn-primary" /></td>
            </tr>
        }
    </table>
</div>

<input type="button" value="Add office" onclick="@("window.location.href='" + @Url.Action("CreateView", "Office") + "'");" class="btn btn-primary" />

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Office/UpdateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.OfficeVM

@{
    ViewData["Title"] = "Edit office";
}

<h4>Update office</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div class="form-group">
                <input hidden asp-for="Id" value="@Model.Id" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" value="@Model.Adress" class="form-control" required />
            </div>
            <div class="form-group">
                <label asp-for="CabinetsCount" class="control-label">Cabinets count</label>
                <input asp-for="CabinetsCount" value="@Model.CabinetsCount" class="form-control" type="number" min="1" required />
            </div>
            <div class="form-group">
                <input type="submit" value="Update" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Program/CreateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.ProgramVM

@{
    ViewData["Title"] = "Create studying program";
}

<h4>Create studying program</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="InternshipId" class="control-label">Internship</label>
                <select asp-for="InternshipId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["Internships"])" required></select>
            </div>
            <div class="form-group">
                <label asp-for="CourseId" class="control-label">Office</label>
                <select asp-for="CourseId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["Courses"])" required></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Program/Index.cshtml
@using NHSDP_Request_handling.WEB.ViewModel;
@model IEnumerable<ProgramVM>
@{
    ViewData["Title"] = "Internship studying programs";
}

<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Internship ID</th>
            <th>Course ID</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (ProgramVM sp in Model)
        {
            <tr>
                <td>@sp.Id.ToString().Substring(0, 10) ...</td>
                <td>@sp.InternshipId</td>
                <td>@sp.CourseId</td>
                <td><input type="button" value="Delete" onclick="@("window.location.href='" + @Url.Action("Delete", "Program") + "?id=" + sp.Id + "'");" class="btn btn-primary" /></td>
            </tr>
        }
    </table>
</div>

<input type="button" value="Add studying program" onclick="@("window.location.href='" + @Url.Action("CreateView", "Program") + "'");" class="btn btn-primary" />

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/Shared/_Layout.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NHSDP_Request_handling.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Office" asp-action="Index">NHSDP - Request handling</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Office" asp-action="Index">Offices</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Internship" asp-action="Index">Internships</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/StudyingPlace/CreateView.cshtml
@model NHSDP_Request_handling.WEB.ViewModel.StudyingPlaceVM

@{
    ViewData["Title"] = "Add studying place";
}

<h4>Add studying place</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="InternshipId" class="control-label">Internship</label>
                <select asp-for="InternshipId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["Internships"])" required></select>
            </div>
            <div class="form-group">
                <label asp-for="OfficeId" class="control-label">Office</label>
                <select asp-for="OfficeId" class="form-control" asp-items="@((List<SelectListItem>)ViewData["Offices"])" required></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>
<p style="color: darkred;">@TempData["Message"]</p>

NHSDP_Request_handling/NHSDP_Request_handling.WEB/Views/StudyingPlace/Index.cshtml
@using NHSDP_Request_handling.WEB.ViewModel;
@model IEnumerable<StudyingPlaceVM>
@{
    ViewData["Title"] = "Studying places";
}

<div>
    <table>
        <tr>
            <th>ID</th>
            <th>Internship ID</th>
            <th>Office ID</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (StudyingPlaceVM sp in Model)
        {
            <tr>
                <td>@sp.Id.ToString().Substring(0, 10) ...</td>
                <td>@sp.InternshipId</td>
                <td>@sp.OfficeId</td>
                <td><input type="button" value="Delete" onclick="@("window.location.href='" + @Url.Action("Delete", "StudyingPlace") + "?id=" + sp.Id + "'");" class="btn btn-primary" /></td>
            </tr>
        }
    </table>
</div>

<input type="button" value="Add studying place" onclick="@("window.location.href='" + @Url.Action("CreateView", "StudyingPlace") + "'");" class="btn btn-primary" />
<p style="color: red;">@ViewData["ActionResultMessage"]</p>